// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package wire

import (
	"github.com/go-zs/go-demo/di/wiredemo/constructor"
)

// Injectors from wire.go:

func InitializeEvent(msg string) constructor.Event {
	message := constructor.NewMessage(msg)
	greeter := constructor.NewGreeter(message)
	eventEvent := constructor.NewEvent(greeter)
	return eventEvent
}
